uploads = []
outputs = []

[[generated]]
id = "zzsvOwWeX-Z7A70-kY7UO"
uri = "file://artifacts/nu-birth-fitness/public/icon-512.png"
type = "image"
title = "NU Birth Fitness App Icon"

[[generated]]
id = "e81at4flJ67V30Tze0fbZ"
uri = "file://artifacts/nu-birth-fitness/public/hero-bg.png"
type = "image"
title = "Hero background abstract"
